FROM golang:1.20

RUN  sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list  && \
    apt update -y && apt install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 upx python2 python3 -y && apt autoclean && apt clean
ENV GOPROXY=https://goproxy.cn
RUN go install mvdan.cc/garble@latest